@startuml
'https://plantuml.com/class-diagram


top to bottom direction

package "API" {
  class EmissionsCalculatorController
  class TouristController
  class TransportMediumController
}


package "Persistence" {
  class TransportMediumPersistenceService {}
  class TouristPersistenceService {}
}


package "Core" <<Database>> {
  top to bottom direction
  package transport {
    class TransportMedium {
      -long transportId
      -String transportName
      -TransportMediumType transportType
      -double emissions
    }
    enum TransportMediumType {
      CAR_PETROL_SMALL
      CAR_PETROL_MEDIUM
      CAR_PETROL_LARGE
      CAR_DIESEL_SMALL
      CAR_DIESEL_MEDIUM
      CAR_DIESEL_LARGE
      BIKE
      FOOT
      TRAIN
      CAR_HYBRID
      CAR_ELECTRIC
    }
    class TransportMediumService {
      -TransportMedium vehicle
      +findTransportMediumById()
      +findAllTransportMedium()
      +createTransportMedium()
      +updateTransportMedium()
      +deleteTransportMedium()
    }
    TransportMedium -[hidden]down- TransportMediumType

    TransportMediumType -[hidden]down- TransportMediumService
  }

  package tourist {
     class Tourist {
     -String touristName
     -String touristSecurityQuestion
     -String touristSecurityQuestionAnswer
    }
    class TouristService {
     +Tourist findTouristById()
     +Tourist findAllTourists()
     +Tourist createTourist()
     +Tourist updateTourist()
     +Tourist deleteTourist()
    }
    class TouristEmission {
      -Tourist tourist
      -TransportMedium vehicle
      -double emissions
      +double calculateEmissionsForTourist()
    }
    Tourist -[hidden]down- TouristService

    TouristService -[hidden]down- TouristEmission
  }

  package emissions {
     class EmissionsCalculatorService {
      -TransportMedium vehicle
      -double distance
      +double calculateEmissions()
    }
  }

  package distance {
    class DistanceCalculatorService {
      +double calculateDistance(Point start, Point end)
    }
    class CoordinateService {
      +Point getCoordinatesFromCity(String city)
    }
    DistanceCalculatorService -[hidden]down- CoordinateService
  }

}

  top to bottom direction

"Core" -up-> "API"

"Core" -down-> "Persistence"

@enduml